#!/bin/bash
#
# HomeGuard Installation Script
#
# This script installs HomeGuard on macOS:
# 1. Creates necessary directories
# 2. Installs binary and configuration files
# 3. Sets up PF firewall rules
# 4. Installs and starts LaunchDaemon service
#
# Usage: sudo ./install.sh [options]
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"

# Installation paths
BIN_DIR="/usr/local/bin"
ETC_DIR="/usr/local/etc/homeguard"
VAR_DIR="/var/lib/homeguard"
LOG_DIR="/var/log/homeguard"
LAUNCHD_DIR="/Library/LaunchDaemons"

# File names
BINARY_NAME="homeguard"
PLIST_NAME="com.homeguard.plist"
CONFIG_NAME="homeguard.toml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Check root privileges
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (sudo)"
        exit 1
    fi
}

# Check macOS version
check_macos() {
    if [[ "$(uname)" != "Darwin" ]]; then
        log_error "This script only supports macOS"
        exit 1
    fi

    local version=$(sw_vers -productVersion)
    log_info "macOS version: ${version}"

    # Check minimum version (10.15 Catalina or later)
    local major=$(echo "$version" | cut -d. -f1)
    if [[ "$major" -lt 10 ]]; then
        log_error "macOS 10.15 or later is required"
        exit 1
    fi
}

# Check if binary exists
check_binary() {
    local binary_path="${PROJECT_DIR}/target/release/${BINARY_NAME}"

    if [[ ! -f "$binary_path" ]]; then
        log_warn "Release binary not found at: ${binary_path}"
        log_info "Attempting to build..."

        if command -v cargo &>/dev/null; then
            cd "${PROJECT_DIR}"
            cargo build --release
        else
            log_error "Cargo not found. Please build the project first:"
            echo "  cd ${PROJECT_DIR}"
            echo "  cargo build --release"
            exit 1
        fi
    fi

    if [[ ! -f "$binary_path" ]]; then
        log_error "Failed to build binary"
        exit 1
    fi

    echo "$binary_path"
}

# Create directories
create_directories() {
    log_step "Creating directories..."

    mkdir -p "${BIN_DIR}"
    mkdir -p "${ETC_DIR}"
    mkdir -p "${ETC_DIR}/rules"
    mkdir -p "${ETC_DIR}/blocklists"
    mkdir -p "${VAR_DIR}"
    mkdir -p "${VAR_DIR}/logs"
    mkdir -p "${LOG_DIR}"

    # Set permissions
    chmod 755 "${ETC_DIR}"
    chmod 700 "${VAR_DIR}"
    chmod 755 "${LOG_DIR}"

    log_info "Directories created"
}

# Install binary
install_binary() {
    local source_binary=$1

    log_step "Installing binary..."

    cp "${source_binary}" "${BIN_DIR}/${BINARY_NAME}"
    chmod 755 "${BIN_DIR}/${BINARY_NAME}"

    log_info "Binary installed to ${BIN_DIR}/${BINARY_NAME}"
}

# Install configuration
install_config() {
    log_step "Installing configuration..."

    local source_config="${PROJECT_DIR}/config/${CONFIG_NAME}"
    local dest_config="${ETC_DIR}/${CONFIG_NAME}"

    if [[ -f "${dest_config}" ]]; then
        log_warn "Configuration file already exists: ${dest_config}"
        log_warn "Backing up to ${dest_config}.backup"
        cp "${dest_config}" "${dest_config}.backup"
    fi

    if [[ -f "${source_config}" ]]; then
        # Copy and update paths for production
        sed -e "s|blocklist_dir = \"blocklists\"|blocklist_dir = \"${ETC_DIR}/blocklists\"|g" \
            -e "s|database = \".*\"|database = \"${VAR_DIR}/config.db\"|g" \
            -e "s|log_dir = \".*\"|log_dir = \"${VAR_DIR}/logs\"|g" \
            -e "s|rule_file = \"./rules.list\"|rule_file = \"${ETC_DIR}/rules.list\"|g" \
            -e "s|rules_dir = \"./rules\"|rules_dir = \"${ETC_DIR}/rules\"|g" \
            "${source_config}" > "${dest_config}"
    else
        # Create default configuration
        cat > "${dest_config}" << EOF
# HomeGuard Configuration
# Generated by install.sh

[general]
log_level = "info"

[dns]
listen = "127.0.0.1:5353"
upstream = ["8.8.8.8:53", "1.1.1.1:53"]
fake_dns = true
fake_dns_pool = "198.18.0.0/15"
cache_size = 10000
cache_ttl = 300

[transparent]
listen = "127.0.0.1:7893"

[parental]
enabled = false
blocklist_dir = "${ETC_DIR}/blocklists"
global_categories = []
default_policy = "allow"
log_blocked = true

[storage]
database = "${VAR_DIR}/config.db"

[logging]
log_dir = "${VAR_DIR}/logs"
granularity = 2
retention_days = 30

[rules]
geoip_db = ""
rule_file = "${ETC_DIR}/rules.list"
rules_dir = "${ETC_DIR}/rules"

[proxy]
# Add Shadowsocks proxies here
# [[proxy.shadowsocks]]
# name = "my-proxy"
# server = "proxy.example.com"
# port = 8388
# password = "password"
# method = "chacha20-ietf-poly1305"
EOF
    fi

    chmod 644 "${dest_config}"
    log_info "Configuration installed to ${dest_config}"

    # Install rule list file
    local source_rules="${PROJECT_DIR}/config/rules.list"
    local dest_rules="${ETC_DIR}/rules.list"
    if [[ -f "${dest_rules}" ]]; then
        log_warn "Rule list already exists: ${dest_rules} (kept as-is, no overwrite)"
    elif [[ -f "${source_rules}" ]]; then
        cp "${source_rules}" "${dest_rules}"
        chmod 644 "${dest_rules}"
        log_info "Rule list installed to ${dest_rules}"
    else
        cat > "${dest_rules}" << 'EOF'
# HomeGuard Rule List
# One rule per line. `#` for comments. See docs/phase3-rule-engine.md.
FINAL,DIRECT
EOF
        chmod 644 "${dest_rules}"
        log_info "Default rule list created at ${dest_rules}"
    fi

    # Copy rule-set files (referenced by RULE-SET inside rules.list) if any
    if [[ -d "${PROJECT_DIR}/config/rules" ]]; then
        cp -r "${PROJECT_DIR}/config/rules/"* "${ETC_DIR}/rules/" 2>/dev/null || true
        log_info "Rule sets copied to ${ETC_DIR}/rules/"
    fi

    # Copy blocklists if exist
    if [[ -d "${PROJECT_DIR}/config/blocklists" ]]; then
        cp -r "${PROJECT_DIR}/config/blocklists/"* "${ETC_DIR}/blocklists/" 2>/dev/null || true
        log_info "Blocklists copied to ${ETC_DIR}/blocklists/"
    fi
}

# Install LaunchDaemon
install_launchd() {
    log_step "Installing LaunchDaemon..."

    local source_plist="${SCRIPT_DIR}/launchd/${PLIST_NAME}"
    local dest_plist="${LAUNCHD_DIR}/${PLIST_NAME}"

    if [[ ! -f "${source_plist}" ]]; then
        log_error "LaunchDaemon plist not found: ${source_plist}"
        exit 1
    fi

    # Unload existing service if running
    if launchctl list | grep -q "com.homeguard"; then
        log_info "Stopping existing service..."
        launchctl unload "${dest_plist}" 2>/dev/null || true
    fi

    cp "${source_plist}" "${dest_plist}"
    chmod 644 "${dest_plist}"
    chown root:wheel "${dest_plist}"

    log_info "LaunchDaemon installed to ${dest_plist}"
}

# Setup PF firewall
setup_pf() {
    log_step "Setting up PF firewall..."

    local pf_script="${SCRIPT_DIR}/setup-pf.sh"

    if [[ ! -f "${pf_script}" ]]; then
        log_error "PF setup script not found: ${pf_script}"
        exit 1
    fi

    chmod +x "${pf_script}"
    "${pf_script}"
}

# Start service
start_service() {
    log_step "Starting HomeGuard service..."

    local dest_plist="${LAUNCHD_DIR}/${PLIST_NAME}"

    launchctl load "${dest_plist}"

    # Wait a moment for service to start
    sleep 2

    if launchctl list | grep -q "com.homeguard"; then
        log_info "HomeGuard service started successfully"
    else
        log_error "Failed to start HomeGuard service"
        log_info "Check logs at: ${LOG_DIR}/homeguard.log"
        exit 1
    fi
}

# Verify installation
verify_installation() {
    log_step "Verifying installation..."

    local errors=0

    # Check binary
    if [[ -x "${BIN_DIR}/${BINARY_NAME}" ]]; then
        log_info "Binary: OK"
    else
        log_error "Binary: FAILED"
        ((errors++))
    fi

    # Check config
    if [[ -f "${ETC_DIR}/${CONFIG_NAME}" ]]; then
        log_info "Configuration: OK"
    else
        log_error "Configuration: FAILED"
        ((errors++))
    fi

    # Check LaunchDaemon
    if launchctl list | grep -q "com.homeguard"; then
        log_info "Service: RUNNING"
    else
        log_warn "Service: NOT RUNNING"
    fi

    # Check PF
    if pfctl -s nat 2>/dev/null | grep -q "127.0.0.1"; then
        log_info "PF NAT rules: ACTIVE"
    else
        log_warn "PF NAT rules: INACTIVE"
    fi

    # Check DNS
    if nc -z -u 127.0.0.1 5353 2>/dev/null; then
        log_info "DNS server: LISTENING"
    else
        log_warn "DNS server: NOT LISTENING (may need a moment to start)"
    fi

    if [[ $errors -gt 0 ]]; then
        log_error "Installation completed with errors"
        return 1
    fi

    return 0
}

# Print usage
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --no-pf        Skip PF firewall setup"
    echo "  --no-start     Don't start service after installation"
    echo "  --help         Show this help message"
    echo ""
    echo "This script installs HomeGuard to:"
    echo "  Binary:        ${BIN_DIR}/${BINARY_NAME}"
    echo "  Configuration: ${ETC_DIR}/"
    echo "  Data:          ${VAR_DIR}/"
    echo "  Logs:          ${LOG_DIR}/"
    echo "  Service:       ${LAUNCHD_DIR}/${PLIST_NAME}"
}

# Main function
main() {
    local skip_pf=false
    local skip_start=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --no-pf)
                skip_pf=true
                shift
                ;;
            --no-start)
                skip_start=true
                shift
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    echo ""
    echo "=========================================="
    echo "       HomeGuard Installation Script      "
    echo "=========================================="
    echo ""

    # Pre-flight checks
    check_root
    check_macos

    # Find binary
    local binary_path=$(check_binary)
    log_info "Using binary: ${binary_path}"

    # Installation steps
    create_directories
    install_binary "${binary_path}"
    install_config
    install_launchd

    if [[ "$skip_pf" == false ]]; then
        setup_pf
    else
        log_warn "Skipping PF setup (--no-pf)"
    fi

    if [[ "$skip_start" == false ]]; then
        start_service
    else
        log_warn "Skipping service start (--no-start)"
    fi

    # Verify
    echo ""
    verify_installation

    echo ""
    echo "=========================================="
    echo "       Installation Complete!             "
    echo "=========================================="
    echo ""
    echo "Configuration: ${ETC_DIR}/${CONFIG_NAME}"
    echo "Logs:          ${LOG_DIR}/homeguard.log"
    echo ""
    echo "Useful commands:"
    echo "  sudo launchctl stop com.homeguard    # Stop service"
    echo "  sudo launchctl start com.homeguard   # Start service"
    echo "  tail -f ${LOG_DIR}/homeguard.log     # View logs"
    echo ""
    echo "To uninstall: sudo ${SCRIPT_DIR}/uninstall.sh"
    echo ""
}

main "$@"
