#!/bin/bash
#
# HomeGuard PF Firewall Setup Script
#
# This script configures macOS PF (Packet Filter) to redirect:
# - DNS traffic (UDP 53) to HomeGuard DNS server
# - HTTP/HTTPS traffic (TCP 80, 443) to HomeGuard transparent proxy
#
# Usage: sudo ./setup-pf.sh [interface]
#        sudo ./setup-pf.sh en0
#        sudo ./setup-pf.sh --disable
#

set -e

# Configuration
ANCHOR_NAME="com.homeguard"
ANCHOR_FILE="/etc/pf.anchors/${ANCHOR_NAME}"
PF_CONF="/etc/pf.conf"
PF_CONF_BACKUP="/etc/pf.conf.homeguard.backup"
DNS_PORT=5353
PROXY_PORT=7893

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check root privileges
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (sudo)"
        exit 1
    fi
}

# Detect primary network interface
detect_interface() {
    # Try to get the default route interface
    local iface=$(route -n get default 2>/dev/null | grep 'interface:' | awk '{print $2}')

    if [[ -z "$iface" ]]; then
        # Fallback: try to find an active interface
        iface=$(ifconfig | grep -E '^en[0-9]+:' | head -1 | cut -d: -f1)
    fi

    echo "$iface"
}

# Create PF anchor file
create_anchor() {
    local interface=$1

    log_info "Creating PF anchor file: ${ANCHOR_FILE}"

    cat > "${ANCHOR_FILE}" << EOF
# HomeGuard PF Anchor Rules
# Generated by setup-pf.sh
# Interface: ${interface}

# Skip localhost traffic (already handled)
set skip on lo0

# NAT Redirect Rules for interface ${interface}

# Redirect DNS (UDP 53) to HomeGuard DNS server
rdr pass on ${interface} inet proto udp from any to any port 53 -> 127.0.0.1 port ${DNS_PORT}

# Redirect HTTP (TCP 80) to HomeGuard transparent proxy
rdr pass on ${interface} inet proto tcp from any to any port 80 -> 127.0.0.1 port ${PROXY_PORT}

# Redirect HTTPS (TCP 443) to HomeGuard transparent proxy
rdr pass on ${interface} inet proto tcp from any to any port 443 -> 127.0.0.1 port ${PROXY_PORT}

# Pass all other traffic
pass all
EOF

    chmod 644 "${ANCHOR_FILE}"
    log_info "Anchor file created successfully"
}

# Backup original pf.conf
backup_pf_conf() {
    if [[ ! -f "${PF_CONF_BACKUP}" ]]; then
        log_info "Backing up ${PF_CONF} to ${PF_CONF_BACKUP}"
        cp "${PF_CONF}" "${PF_CONF_BACKUP}"
    else
        log_info "Backup already exists: ${PF_CONF_BACKUP}"
    fi
}

# Check if HomeGuard anchor is already in pf.conf
is_anchor_configured() {
    grep -q "rdr-anchor \"${ANCHOR_NAME}\"" "${PF_CONF}" 2>/dev/null
}

# Add HomeGuard anchor to pf.conf
configure_pf_conf() {
    if is_anchor_configured; then
        log_info "HomeGuard anchor already configured in ${PF_CONF}"
        return 0
    fi

    log_info "Adding HomeGuard anchor to ${PF_CONF}"

    # Create a temporary file with the new configuration
    local temp_file=$(mktemp)

    # Read existing pf.conf and insert anchor rules after the first rdr-anchor line
    # or at the beginning if no rdr-anchor exists
    local inserted=false
    while IFS= read -r line || [[ -n "$line" ]]; do
        echo "$line" >> "$temp_file"

        # Insert after first rdr-anchor line if exists
        if [[ "$line" =~ ^rdr-anchor && "$inserted" == false ]]; then
            echo "" >> "$temp_file"
            echo "# HomeGuard anchor" >> "$temp_file"
            echo "rdr-anchor \"${ANCHOR_NAME}\"" >> "$temp_file"
            inserted=true
        fi
    done < "${PF_CONF}"

    # If no rdr-anchor was found, add at the beginning (after scrub rules if any)
    if [[ "$inserted" == false ]]; then
        # Insert before first pass/block rule
        local temp_file2=$(mktemp)
        local rules_started=false

        echo "# HomeGuard anchor" > "$temp_file2"
        echo "rdr-anchor \"${ANCHOR_NAME}\"" >> "$temp_file2"
        echo "" >> "$temp_file2"

        while IFS= read -r line || [[ -n "$line" ]]; do
            echo "$line" >> "$temp_file2"
        done < "${PF_CONF}"

        mv "$temp_file2" "$temp_file"
    fi

    # Also add the load anchor line at the end
    echo "" >> "$temp_file"
    echo "# Load HomeGuard anchor rules" >> "$temp_file"
    echo "load anchor \"${ANCHOR_NAME}\" from \"${ANCHOR_FILE}\"" >> "$temp_file"

    # Replace pf.conf
    mv "$temp_file" "${PF_CONF}"
    chmod 644 "${PF_CONF}"

    log_info "PF configuration updated"
}

# Enable and reload PF
enable_pf() {
    log_info "Enabling PF firewall..."

    # Check syntax
    if ! pfctl -n -f "${PF_CONF}" 2>/dev/null; then
        log_error "PF configuration syntax error!"
        pfctl -n -f "${PF_CONF}"
        exit 1
    fi

    # Enable PF
    pfctl -e 2>/dev/null || true

    # Load rules
    pfctl -f "${PF_CONF}"

    log_info "PF firewall enabled and rules loaded"
}

# Disable HomeGuard PF rules
disable_pf() {
    log_info "Disabling HomeGuard PF rules..."

    # Remove anchor file
    if [[ -f "${ANCHOR_FILE}" ]]; then
        rm -f "${ANCHOR_FILE}"
        log_info "Removed anchor file: ${ANCHOR_FILE}"
    fi

    # Restore original pf.conf if backup exists
    if [[ -f "${PF_CONF_BACKUP}" ]]; then
        cp "${PF_CONF_BACKUP}" "${PF_CONF}"
        log_info "Restored original PF configuration"
    else
        # Remove HomeGuard lines from pf.conf
        local temp_file=$(mktemp)
        grep -v -E "(HomeGuard|${ANCHOR_NAME})" "${PF_CONF}" > "$temp_file" || true
        mv "$temp_file" "${PF_CONF}"
        log_info "Removed HomeGuard rules from PF configuration"
    fi

    # Reload PF
    pfctl -f "${PF_CONF}" 2>/dev/null || true

    log_info "HomeGuard PF rules disabled"
}

# Show current status
show_status() {
    echo ""
    echo "=== PF Status ==="
    pfctl -s info 2>/dev/null | head -5

    echo ""
    echo "=== NAT Rules ==="
    pfctl -s nat 2>/dev/null || echo "No NAT rules"

    echo ""
    echo "=== HomeGuard Anchor ==="
    if [[ -f "${ANCHOR_FILE}" ]]; then
        cat "${ANCHOR_FILE}"
    else
        echo "Anchor file not found"
    fi
}

# Print usage
usage() {
    echo "Usage: $0 [OPTIONS] [interface]"
    echo ""
    echo "Options:"
    echo "  --disable    Disable HomeGuard PF rules"
    echo "  --status     Show current PF status"
    echo "  --help       Show this help message"
    echo ""
    echo "Arguments:"
    echo "  interface    Network interface to redirect traffic from (e.g., en0, en1)"
    echo "               If not specified, auto-detects the default interface"
    echo ""
    echo "Examples:"
    echo "  sudo $0              # Auto-detect interface and enable"
    echo "  sudo $0 en0          # Use en0 interface"
    echo "  sudo $0 --disable    # Disable HomeGuard rules"
    echo "  sudo $0 --status     # Show current status"
}

# Main function
main() {
    check_root

    case "${1:-}" in
        --help|-h)
            usage
            exit 0
            ;;
        --disable)
            disable_pf
            exit 0
            ;;
        --status)
            show_status
            exit 0
            ;;
        --*)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac

    # Get interface
    local interface="${1:-}"
    if [[ -z "$interface" ]]; then
        interface=$(detect_interface)
        if [[ -z "$interface" ]]; then
            log_error "Could not detect network interface. Please specify one manually."
            usage
            exit 1
        fi
        log_info "Auto-detected interface: ${interface}"
    fi

    # Verify interface exists
    if ! ifconfig "$interface" >/dev/null 2>&1; then
        log_error "Interface '${interface}' does not exist"
        echo "Available interfaces:"
        ifconfig -l
        exit 1
    fi

    log_info "Setting up HomeGuard PF rules for interface: ${interface}"

    # Setup steps
    backup_pf_conf
    create_anchor "$interface"
    configure_pf_conf
    enable_pf

    echo ""
    log_info "HomeGuard PF setup complete!"
    echo ""
    echo "Traffic redirection configured:"
    echo "  - DNS (UDP 53) -> 127.0.0.1:${DNS_PORT}"
    echo "  - HTTP (TCP 80) -> 127.0.0.1:${PROXY_PORT}"
    echo "  - HTTPS (TCP 443) -> 127.0.0.1:${PROXY_PORT}"
    echo ""
    echo "To disable: sudo $0 --disable"
    echo "To check status: sudo $0 --status"
}

main "$@"
